//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQToolShared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQToolShared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloth Cap,Cloth Veil,Cloth Choker,Cloth Shirt,Cloth Shawl,Cloth Cape,Cloth Cord,Cloth Sleeves,Cloth Wristband,Cloth Gloves,Cloth Pants,Cloth Sandals,Small Cloth Cap,Small Cloth Veil,Small Cloth Choker,Small Cloth Shirt,Small Cloth Shawl,Small Cloth Cape,Small Cloth Cord,Small Cloth Sleeves,Small Cloth Wristband,Small Cloth Gloves,Small Cloth Pants,Small Cloth Sandals,Large Cloth Cap,Large Cloth Veil,Large Cloth Choker,Large Cloth Shirt,Large Cloth Shawl,Large Cloth Cape,Large Cloth Cord,Large Cloth Sleeves, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterItemList {
            get {
                return ResourceManager.GetString("MasterItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a pit trap,a grimling skullcracker,AntiSpawnMan,a grimling high priest,a summoned hatchling,the grimling archmage,a wormbait minnow,a grimling warder,a furious apprentice,a fallen Vah Shir hero,a diseased grimling,EvInvis,A growl,Gatturg Deadface,Gruj Warfist,a skeletal enforcer,WDTrpMn,a grimling apprentice,Foreman Gworknop,a grimling deathguard,a grimling elite guard,Invis,a grimling herbalist,a possessed priest,Trondol Shir,Shackle,a smudged grimling,AnimMan,As,Tashakhi,a grimling manaseeker,a grimling d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterNPCList {
            get {
                return ResourceManager.GetString("MasterNPCList", resourceCulture);
            }
        }
    }
}
