//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt; 
        ///    &lt;configSections&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.8&quot; /&gt;
        ///    &lt;/startup&gt; 
        ///  &lt;runtime&gt;
        ///	  &lt;gcServer enabled=&quot;true&quot; /&gt;
        ///	  &lt;gcConcurrent enabled=&quot;true&quot; /&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;System.Memory&quot; publicKeyToken=&quot;cc7b13ffcd2ddd51&quot; culture=&quot;neutral&quot; /&gt;
        ///        &lt;bindingRedirec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dps {
            get {
                object obj = ResourceManager.GetObject("dps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HyperlinkForward {
            get {
                object obj = ResourceManager.GetObject("HyperlinkForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_folder {
            get {
                object obj = ResourceManager.GetObject("open_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pig {
            get {
                object obj = ResourceManager.GetObject("pig", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon sickpic {
            get {
                object obj = ResourceManager.GetObject("sickpic", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[Mon Nov 21 16:56:58 2022] An ancient shard wyvern hits Huntor for 342 points of damage.
        ///[Mon Nov 21 16:56:58 2022] An ancient shard wyvern hits Huntor for 364 points of damage.
        ///[Mon Nov 21 16:56:59 2022] Huntor pierces an ancient shard wyvern for 7 points of damage.
        ///[Mon Nov 21 16:57:00 2022] Haripotter begins to cast a spell.
        ///[Mon Nov 21 16:57:00 2022] Dany begins to cast a spell.
        ///[Mon Nov 21 16:57:00 2022] Huntor Scores a critical hit!(66)
        ///[Mon Nov 21 16:57:02 2022] Your Location is -645.07, -173 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestFight {
            get {
                return ResourceManager.GetString("TestFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Mon Dec 19 17:34:52 2022] You slash an ancient tigerclaw racnar for 46 points of damage.
        ///[Mon Dec 19 17:34:52 2022] You slash an ancient tigerclaw racnar for 136 points of damage.
        ///[Mon Dec 19 17:34:52 2022] Mandair pierces an ancient tigerclaw racnar for 38 points of damage.
        ///[Mon Dec 19 17:34:52 2022] Mandair pierces an ancient tigerclaw racnar for 38 points of damage.
        ///[Mon Dec 19 17:34:52 2022] Mandair slashes an ancient tigerclaw racnar for 21 points of damage.
        ///[Mon Dec 19 17:34:52 2022] Mandair sla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestFight2 {
            get {
                return ResourceManager.GetString("TestFight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sun Apr 23 08:43:28 2023] You have entered Plane of Mischief. 
        ///[Sun Apr 23 08:43:30 2023] Your Location is 1939.00, -519.00, -6.25
        ///[Sun Apr 23 08:43:32 2023] Your Location is 1939.00, -519.00, -6.25
        ///[Sun Apr 23 08:43:32 2023] Your Location is 1934.45, -512.79, -6.25
        ///[Sun Apr 23 08:43:35 2023] Your Location is 699.60, -154.62, 178.69
        ///[Sun Apr 23 08:43:35 2023] Your Location is 705.28, -164.76, 178.69
        ///[Sun Apr 23 08:43:36 2023] Your Location is 687.09, -127.18, 178.69
        ///[Sun Apr 23 08:43:37 2023] Your L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testmap {
            get {
                return ResourceManager.GetString("testmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolbox {
            get {
                object obj = ResourceManager.GetObject("toolbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
