using System;

namespace EQToolShared.PQModels
{
    [Serializable]
    public class item
    {
        public int id { get; set; }
        public int minstatus { get; set; }
        public string Name { get; set; }
        public int aagi { get; set; }
        public int ac { get; set; }
        public int acha { get; set; }
        public int adex { get; set; }
        public int aint { get; set; }
        public int asta { get; set; }
        public int astr { get; set; }
        public int awis { get; set; }
        public int bagsize { get; set; }
        public int bagslots { get; set; }
        public int bagtype { get; set; }
        public int bagwr { get; set; }
        public int banedmgamt { get; set; }
        public int banedmgbody { get; set; }
        public int banedmgrace { get; set; }
        public int bardtype { get; set; }
        public int bardvalue { get; set; }
        public int book { get; set; }
        public int casttime { get; set; }
        public int casttime_ { get; set; }
        public int classes { get; set; }
        public uint color { get; set; }
        public int price { get; set; }
        public int cr { get; set; }
        public int damage { get; set; }
        public int deity { get; set; }
        public int delay { get; set; }
        public int dr { get; set; }
        public int clicktype { get; set; }
        public int clicklevel2 { get; set; }
        public int elemdmgtype { get; set; }
        public int elemdmgamt { get; set; }
        public int factionamt1 { get; set; }
        public int factionamt2 { get; set; }
        public int factionamt3 { get; set; }
        public int factionamt4 { get; set; }
        public int factionmod1 { get; set; }
        public int factionmod2 { get; set; }
        public int factionmod3 { get; set; }
        public int factionmod4 { get; set; }
        public string filename { get; set; }
        public int focuseffect { get; set; }
        public int fr { get; set; }
        public int fvnodrop { get; set; }
        public int clicklevel { get; set; }
        public int hp { get; set; }
        public int icon { get; set; }
        public string idfile { get; set; }
        public int itemclass { get; set; }
        public int itemtype { get; set; }
        public int light { get; set; }
        public string lore { get; set; }
        public int magic { get; set; }
        public int mana { get; set; }
        public int material { get; set; }
        public int maxcharges { get; set; }
        public int mr { get; set; }
        public int nodrop { get; set; }
        public int norent { get; set; }
        public int pr { get; set; }
        public int procrate { get; set; }
        public int races { get; set; }
        public int range { get; set; }
        public int reclevel { get; set; }
        public int recskill { get; set; }
        public int reqlevel { get; set; }
        public float sellrate { get; set; }
        public int size { get; set; }
        public int skillmodtype { get; set; }
        public int skillmodvalue { get; set; }
        public int slots { get; set; }
        public int clickeffect { get; set; }
        public int tradeskills { get; set; }
        public int weight { get; set; }
        public int booktype { get; set; }
        public int recastdelay { get; set; }
        public int recasttype { get; set; }
        public DateTime updated { get; set; }
        public string comment { get; set; }
        public int stacksize { get; set; }
        public int stackable { get; set; }
        public int proceffect { get; set; }
        public int proctype { get; set; }
        public int proclevel2 { get; set; }
        public int proclevel { get; set; }
        public int worneffect { get; set; }
        public int worntype { get; set; }
        public int wornlevel2 { get; set; }
        public int wornlevel { get; set; }
        public int focustype { get; set; }
        public int focuslevel2 { get; set; }
        public int focuslevel { get; set; }
        public int scrolleffect { get; set; }
        public int scrolltype { get; set; }
        public int scrolllevel2 { get; set; }
        public int scrolllevel { get; set; }
        public DateTime? serialized { get; set; }
        public DateTime? verified { get; set; }
        public string serialization { get; set; }
        public string source { get; set; }
        public string lorefile { get; set; }
        public int questitemflag { get; set; }
        public int clickunk5 { get; set; }
        public string clickunk6 { get; set; }
        public int clickunk7 { get; set; }
        public int procunk1 { get; set; }
        public int procunk2 { get; set; }
        public int procunk3 { get; set; }
        public int procunk4 { get; set; }
        public string procunk6 { get; set; }
        public int procunk7 { get; set; }
        public int wornunk1 { get; set; }
        public int wornunk2 { get; set; }
        public int wornunk3 { get; set; }
        public int wornunk4 { get; set; }
        public int wornunk5 { get; set; }
        public string wornunk6 { get; set; }
        public int wornunk7 { get; set; }
        public int focusunk1 { get; set; }
        public int focusunk2 { get; set; }
        public int focusunk3 { get; set; }
        public int focusunk4 { get; set; }
        public int focusunk5 { get; set; }
        public string focusunk6 { get; set; }
        public int focusunk7 { get; set; }
        public int scrollunk1 { get; set; }
        public int scrollunk2 { get; set; }
        public int scrollunk3 { get; set; }
        public int scrollunk4 { get; set; }
        public int scrollunk5 { get; set; }
        public string scrollunk6 { get; set; }
        public int scrollunk7 { get; set; }
        public string clickname { get; set; }
        public string procname { get; set; }
        public string wornname { get; set; }
        public string focusname { get; set; }
        public string scrollname { get; set; }
        public string created { get; set; }
        public int bardeffect { get; set; }
        public int bardeffecttype { get; set; }
        public int bardlevel2 { get; set; }
        public int bardlevel { get; set; }
        public int bardunk1 { get; set; }
        public int bardunk2 { get; set; }
        public int bardunk3 { get; set; }
        public int bardunk4 { get; set; }
        public int bardunk5 { get; set; }
        public string bardname { get; set; }
        public int bardunk7 { get; set; }
        public int gmflag { get; set; }
        public int soulbound { get; set; }
    }
}
